language: java
jdk: oraclejdk8
addons:
  sonalcloud:
    organization: afcabezasq-github
    token:
      secure: 43eea2c33e5af8418fb21544d5c8eb87e624511f
script:
  ./gradlew clean check build
cache:
  directories:
    $HOME/.m2/repository
    $HOME/.sonar/cache
    $HOME/.gradle
    .gradle

