language: java

addons:
  sonarcloud:
    organization: "afcabezasq"
    token:
      secure: "1198ecfa2ca5c62054bcb3c71120583c0b862bdf" # encrypted value of your token

before_script: cd Pruebas/HelloWorld1
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=afcabezasq_SharkFeather